"""buat table eyeglasses

Revision ID: 7bf487d4b397
Revises: 860495cb5b3f
Create Date: 2024-05-02 22:14:56.865377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf487d4b397'
down_revision = '860495cb5b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eyeglasses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('faceShape', sa.String(length=15), nullable=True),
    sa.Column('price', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('frameColour', sa.String(length=100), nullable=True),
    sa.Column('frameShape', sa.String(length=20), nullable=True),
    sa.Column('frameStyle', sa.String(length=50), nullable=True),
    sa.Column('linkPic1', sa.String(length=255), nullable=True),
    sa.Column('linkPic2', sa.String(length=255), nullable=True),
    sa.Column('linkPic3', sa.String(length=255), nullable=True),
    sa.Column('frameMaterial', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eyeglasses')
    # ### end Alembic commands ###
